export const Terms = () => {
  return (
    <div className="fade-up">
      <section className="section text-center" style={{ backgroundColor: 'white' }}>
        <div className="container">
          <div className="flex justify-center mb-6">
            <span className="badge badge-amber">Legal Documentation</span>
          </div>
          <h1 style={{ fontSize: 'clamp(32px, 5vw, 56px)' }}>Terms & Conditions</h1>
        </div>
      </section>

      <section className="section container">
        <div className="prose">
          <h2>1. Acceptance of Terms</h2>
          <p>
            By accessing and using MediFinder AI, you accept and agree to be bound by the terms and provision 
            of this agreement. In addition, when using these particular services, you shall be subject to any posted 
            guidelines or rules applicable to such services.
          </p>

          <h2>2. Not Medical Advice</h2>
          <p>
            The content provided by MediFinder AI, including but not limited to text, graphics, images, and other material, 
            is for informational purposes only. The content is not intended to be a substitute for professional medical advice, 
            diagnosis, or treatment.
          </p>
          <p>
            Always seek the advice of your physician or other qualified health provider with any questions you may have 
            regarding a medical condition. Never disregard professional medical advice or delay in seeking it because of 
            something you have read on this website.
          </p>

          <h2>3. AI-Generated Content</h2>
          <p>
            You acknowledge that the information provided on this platform is generated dynamically by artificial intelligence. 
            While we strive for accuracy, the information may contain errors, omissions, or outdated information. 
            We do not guarantee the completeness, reliability, or accuracy of the AI-generated responses.
          </p>

          <h2>4. Limitation of Liability</h2>
          <p>
            In no event shall MediFinder AI, nor its directors, employees, partners, agents, suppliers, or affiliates, 
            be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, 
            loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or 
            inability to access or use the service.
          </p>

          <div className="disclaimer-box">
            <h3><span style={{ fontSize: '20px' }}>⚠️</span> Medical Disclaimer Agreement</h3>
            <p>
              By using this site, you explicitly agree that you understand the information provided is generated by AI 
              and must be verified by a licensed healthcare professional before any clinical application or personal use.
            </p>
          </div>
        </div>
      </section>
    </div>
  );
};
