import React from 'react';

export const Terms = () => {
  return (
    <div className="container fade-in">
      <div className="prose card mt-12">
        <h1 className="text-gradient">Terms & Conditions</h1>
        
        <h2>1. Acceptance of Terms</h2>
        <p>
          By accessing and using MediFinder AI, you agree to be bound by these Terms and Conditions. 
          If you do not agree with any part of these terms, you must not use our service.
        </p>

        <h2>2. Medical Disclaimer (CRITICAL)</h2>
        <p>
          <strong>MediFinder AI is NOT a substitute for professional medical advice, diagnosis, or treatment.</strong> 
          The content generated by our AI is for informational purposes only. You must always seek the advice of your 
          physician or other qualified health providers with any questions you may have regarding a medical condition. 
          Never disregard professional medical advice or delay in seeking it because of something you have read on this application.
        </p>

        <h2>3. Liability</h2>
        <p>
          The developers and owners of MediFinder AI shall not be held liable for any direct, indirect, incidental, 
          consequential, or special damages arising out of or in any way connected with your use of our platform 
          or reliance on the information provided.
        </p>

        <h2>4. API Usage</h2>
        <p>
          You are responsible for providing your own valid OpenRouter API key. You agree to abide by OpenRouter's 
          terms of service and usage policies. MediFinder AI is not responsible for any costs incurred through 
          your API usage.
        </p>
      </div>
    </div>
  );
};
